### ISSUE TITLE
Strokes in generated SVGs are too light

### ISSUE THREAD

**Issue by muesli** [tuhiproject/tuhi#109]
Using a Bamboo Folio, the pen strokes generated in the SVG are way too light compared to the paper and original Bamboo Android software.

**Comment by bentiss** [comment]
Thanks for the report.
Could you draw a single stroke on your tablet, fetch the SVG, then edit this SVG in inkscape to match your needs in term of stroke, and finally attach the final SVG here?

**Comment by aicherm** [comment]
I just had a look into this issue. The thing is that my Slate returns a resolution of height="21600" width="29700", which seems to be in 1/100mm,  so setting the stroke-width=5 (kete.py) is really really tiny.
I had as well a look into the SVG export from Inkspace and they seem to scale the page to height="1188.0" width="864.0".
So I would suggest to do the same, since some (of my) image previewers seem to have trouble loading such a high "resolution". I don't know why this makes a difference since the resolution does not really change here. 
An other option would be to just set the stroke-width to something like e.g. 30 or 50.

**Comment by muesli** [comment]
@aicherm I'll try out your PR and will provide some feedback later tonight.

**Comment by aicherm** [comment]
@muesli, great!
I forgot to mention that the division by 10 would fit A4 paper format in height. (Bamboo Slate A4)

**Comment by whot** [comment]
> The thing is that my Slate returns a resolution of height="21600" width="29700", which seems to be in 1/100mm

Checked an SVG from the Intuos Pro Paper and it says `height="29600" width="44800"` which is microns too, but twice as big as the tablet's actual area (w224 * h148mm). That's... strange and should be something we should work around during SVG export.

An empty A4 document saved from Inkscape says `width="210mm" height="297mm"`, maybe we can use the units in svgwrite?

**Comment by whot** [comment]
This code: `svgwrite.Drawing('test.svg', size=('100mm', '100mm')).save()` results in an svg containing `height="100mm" ... width="100mm"`. So I think we should definitely go down the route of writing out the phys. dimensions.

**Comment by aicherm** [comment]
I just noticed something very strange. When exporting to PDF in Inkspace Android App the page is 297 x 216mm, which would correspond to a scaling factor 100 in my case. (A4 297 x 210)
When exporting the same document in Inkspace-Web it is  314 x 229 mm.

**Comment by gbraad** [comment]
Let's assume the Inkspace application is correct.

**Comment by whot** [comment]
so, unless I introduced a bug this should be fixed with tuhi 0.2. the dimensions from the device are in device units and beholden to the device-specific point size. That one is 10 for spark and slate but 5 for the Intuos Pro (despite the device saying 6).

The exported SVGs should reflect whatever we get from the device, so this should be correct now. If not, let's open a new issue please.
