### ISSUE TITLE
Slate Small: unexpected opcode b3 after "get dimensions"

### ISSUE THREAD

**Issue by bartsch** [tuhiproject/tuhi#124]
(Bamboo Slate small, used kete for testing)

- tuhi> enable_live ...
- tuhi> enable_live ... off

Doing the steps above results in an unexpected opcode:
```
DEBUG: tuhi.wacom: Pen left proximity
DEBUG: tuhi.dbus: Live mode stopped on Bamboo Slate for :1.338
DEBUG: tuhi.wacom: FC:D5:9E:C4:DB:B0: starting
DEBUG: tuhi.fw: TX Nordic --> ea / 02 / 03 00
DEBUG: tuhi.fw: RX Nordic <-- b3 01 02
DEBUG: tuhi.wacom: received b3 / 01 / 02
ERROR: tuhi.wacom: **** Exception: unexpected opcode: b3 ****
INFO: tuhi.ble: FC:D5:9E:C4:DB:B0: Disconnecting
INFO: tuhi: unexpected opcode: b3
INFO: tuhi.dbus: An error occured while synching the device
INFO: tuhi.ble: Disconnected
DEBUG: tuhi: FC:D5:9E:C4:DB:B0: disconnected
```
As stated in #117 by @whot ea / 02 / 03 00 is "get dimensions", which doesn't expect a generic ack (b3).

**Comment by gbraad** [comment]
This is not consistent, as I didn't experience this after resetting the device and re-adding.

**Comment by whot** [comment]
I wonder if it's a timing issue, maybe we're connecting too quickly or sending commands too quickly?

**Comment by bentiss** [comment]
Hmm, there is something I don't get here.

```
DEBUG: tuhi.wacom: Pen left proximity
DEBUG: tuhi.dbus: Live mode stopped on Bamboo Slate for :1.338
```
<-- shouldn't we see some TX/RX Nordic here to stop the live mode
```
DEBUG: tuhi.wacom: FC:D5:9E:C4:DB:B0: starting
DEBUG: tuhi.fw: TX Nordic --> ea / 02 / 03 00
...
```
This is a `get_dimensions`, so how was it triggered? By a physical button press? or by the live mode being stopped.

In the first case, I guess we might be missing the live mode stopped Nordic commands as stated after the dbus notification.
In the latter case, that means there is a wrong state in tuhi where the command is transformed from `live mode` to `fetch data`.

In both cases, this seems to be a tuhi issue, not a protocol error.

**Comment by bentiss** [comment]
I actually managed to reproduce it: this happens when the devide is already connected to the host.

So:
- starting `tuhi.py` in a terminal.
- in `kete`: `listen` to the device
- draw something, press the button, the drawing gets fetched.
- leave `kete` (listening stops)
- start `tuhi-live.py` (thus with the connected device)
- `tuhi-live.py` asks for the button pressed -> nothing happens
- `Ctrl-C` -> `tuhi.py` gets that as a fetch of drawing, but we get the `unexpected opcode: b3`

This seems to be a problem when starting the live mode with the device already connected.
