### ISSUE TITLE
registration broken for spark

### ISSUE THREAD

**Issue by human-blip** [tuhiproject/tuhi#148]
somewhere from commit e1a3675439116c00a5bd5e14b5b539b0193db59e onwards registration seems to be broken for Bamboo Spark.

ie. I can register my Spark before that commit but at the latest I cant.

After registering with the earlier version everything else works with the current version.

**Comment by whot** [comment]
Please attach the output when run with `--verbose`, I just tried this with my Spark here on commit 341b91349ef4156758128083b29743190d2c084a and it worked fine.

edit: flag is just `--verbose`

**Comment by human-blip** [comment]
The first two are running tuhi and kete on master

[tuhi-master.log](https://github.com/tuhiproject/tuhi/files/3479519/tuhi-master.log)
[kete-master.log](https://github.com/tuhiproject/tuhi/files/3479520/kete-master.log)

The second two are running tuhi and kete on a branch just prior to commit e1a3675439116c00a5bd5e14b5b539b0193db59e

[tuhi-branch.log](https://github.com/tuhiproject/tuhi/files/3479521/tuhi-branch.log)
[kete-branch.log](https://github.com/tuhiproject/tuhi/files/3479522/kete-branch.log)

**Comment by whot** [comment]
strange. can you put a `print(bluez.vendor_id)` just above that condition please and tell us what's reported here when it doesn't work?

**Comment by human-blip** [comment]
print(blues_device.vendor_id) shows 18261 while the device is in registration mode and 117 otherwise.

**Comment by whot** [comment]
that is strange... the 117 isn't coming from another device by any chance? I have a lot of interference here from neighbours etc. maybe print `bluez_device.address` alongside the vendor id to be sure you have the right device.

18261 is the 0x4755 wacom vendor id, so that one is fine.

also - "shows 18261 while the device is in registration mode", that doesn't match the output you attached above. in that output the tablet is never recognised but if it is in registration mode (blue light blinking) with the right vendor ID, you should see some messages. What happens if you just revert e1a3675 - does it work? If not, then the issue is some other patch after that one.

**Comment by human-blip** [comment]
the 117 was from another stray device.

It looks like the KeyError exception is causing any device not previously seen to not have a chance to register. (ie. re-registration would probably work)

The attached patch fixes it for me.

[base.py.diff.txt](https://github.com/tuhiproject/tuhi/files/3484352/base.py.diff.txt)

**Comment by whot** [comment]
Ah, that explains it. I have too many config files lying around and never wiped it properly.

And your patch is almost there, we just disagree on where the filtering should be one (neither is wrong, I just prefer to filter early). One-line fix in #149, please give that a test. Works here on my spark.

**Comment by human-blip** [comment]
Looks great and works great! Thanks.

**Comment by whot** [comment]
thanks!
