### ISSUE TITLE
Migration form Inkspace (and Visa Versa)

### ISSUE THREAD

**Issue by dmadisetti** [tuhiproject/tuhi#265]
I already have a fair few notes in Inkspace. Any pointers for getting Inkspace drawings into tuhi and visa versa?

**Comment by whot** [comment]
honestly, I don't know. Inkspace is a proprietary app so you'd have to figure out how and where they store the files, then we could *maybe* move our files there, or extract them out of that folder into our SVG format.

Since the files are removed from the device whenever they're downloaded to the host, that's the only possible solution here - we can't re-upload them and then have inkspace download them.

I'm closing this since it's not directly Tuhi related and I have low hopes of us finding time to figure out the Inkspace format (which I expect isn't guaranteed to be stable so it could change any time anyway).
